"""
Roll every raw-sourced/<source>/SOURCE.txt up into one ATTRIBUTION.md.

Wikipedia (CC BY-SA), OpenStax (CC BY 4.0), open-web-math (ODC-By) and
hermes-function-calling-v1 (Apache 2.0, which asks for its NOTICE to be
preserved) all carry attribution obligations. Every source already records
what is needed, verbatim, in its own SOURCE.txt -- nothing rolled them into
one file a released checkpoint or model card could point at. This does that
and nothing else: it is a rollup of data that already exists, no judgement
of its own.

Cheap enough to be a standard step whenever a new source lands in
raw-sourced/ (SORTING_AGENT.md phase 2), not a separate manual chore.

    python3 scripts/build_attribution.py
    python3 scripts/build_attribution.py --self-test

A source directory with no SOURCE.txt, or one with no license field, is
listed loudly in the output rather than skipped -- an attribution file that
quietly omits a source is worse than no attribution file.
"""

import argparse
import os
import re
from pathlib import Path

# Only these are pulled out. SOURCE.txt files carry free-form sections after
# the header block (steam-manuals has a per-title section with its own
# "Game :" / "Directory :" lines); first occurrence of each key wins, so a
# later section cannot overwrite the header.
FIELDS = ("source", "pulled", "license", "files", "size")
FIELD_RE = re.compile(r"^([A-Za-z][A-Za-z ]{0,20}?)\s*:\s?(.*)$")


def parse_source_txt(text: str) -> dict:
    """-> {description, source, pulled, license, files, size} (missing keys absent).

    Format is `key<pad>: value` at column 0 with indented continuation lines,
    preceded by a free-text description. That is the shape every SOURCE.txt in
    this repo uses, copied from data/raw/monolingual/tcy/SOURCE.txt.
    """
    out, desc, current = {}, [], None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            current = None
            continue
        if line[0].isspace():                      # continuation of the last field
            if current:
                out[current] += "\n" + line.strip()
            continue
        m = FIELD_RE.match(line)
        key = m.group(1).strip().lower() if m else None
        if key in FIELDS:
            current = key
            if key not in out:                     # first occurrence wins
                out[key] = m.group(2).strip()
            else:
                current = None                     # a later section's re-use of the name
        else:
            current = None
            if not out:
                desc.append(line.strip())
    if desc:
        out["description"] = " ".join(desc)
    return out


def collect(root: str):
    """-> [(name, parsed_or_None)] for every immediate subdirectory of root."""
    entries = []
    for name in sorted(os.listdir(root)):
        d = os.path.join(root, name)
        if not os.path.isdir(d):
            continue
        src = os.path.join(d, "SOURCE.txt")
        if not os.path.exists(src):
            entries.append((name, None))
            continue
        with open(src, encoding="utf-8", errors="replace") as f:
            entries.append((name, parse_source_txt(f.read())))
    return entries


def render(entries, root: str) -> str:
    out = ["# Attribution",
           "",
           f"Generated by `scripts/build_attribution.py` from each source's own",
           f"`SOURCE.txt` under `{root}`. Do not edit by hand -- edit the SOURCE.txt",
           "and rerun. This is the file that ships with a released checkpoint.",
           "",
           f"{len(entries)} source(s).",
           ""]
    problems = []
    for name, fields in entries:
        out.append(f"## {name}")
        out.append("")
        if fields is None:
            out.append("**No `SOURCE.txt`.** This directory cannot be attributed and must not "
                       "be trained on until it has one (see `data/raw/manual/README.md`).")
            out.append("")
            problems.append(f"{name}: no SOURCE.txt")
            continue
        if fields.get("description"):
            out.append(fields["description"])
            out.append("")
        for key in FIELDS:
            if key in fields:
                value = fields[key].replace("\n", "\n  ")
                out.append(f"- **{key}**: {value}")
        if "license" not in fields:
            out.append("- **license**: **MISSING** -- no license field in this source's SOURCE.txt.")
            problems.append(f"{name}: no license field")
        out.append("")
    if problems:
        out += ["## Problems", "",
                "Sources above that cannot be attributed as-is:", ""]
        out += [f"- {p}" for p in problems]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root", default="data/raw/manual/raw-sourced")
    p.add_argument("--out", default="data/raw/manual/raw-sourced/ATTRIBUTION.md")
    p.add_argument("--self-test", action="store_true")
    args = p.parse_args()

    if args.self_test:
        _self_test()
        return

    entries = collect(args.root)
    text = render(entries, args.root)
    Path(args.out).write_text(text, encoding="utf-8", newline="\n")
    missing = [n for n, f in entries if f is None or "license" not in f]
    print(f"[done] {len(entries)} source(s) -> {args.out}")
    for name, fields in entries:
        lic = "NO SOURCE.txt" if fields is None else fields.get("license", "NO LICENSE FIELD")
        print(f"  {name:<32} {lic.splitlines()[0][:70]}")
    if missing:
        raise SystemExit(f"[warn] {len(missing)} source(s) cannot be attributed: "
                         f"{', '.join(missing)}")


def _self_test():
    import tempfile

    text = ("Two OpenStax textbooks with extracted text.\n"
            "\n"
            "source        : OpenStax (Rice University), https://openstax.org/\n"
            "pulled        : 2026-09-02\n"
            "files         : 4 files\n"
            "                - a.txt (10 bytes)\n"
            "size          : 58,296,598 bytes\n"
            "license       : CC BY 4.0. Quoted verbatim from the colophon:\n"
            '                "content is licensed under a Creative Commons Attribution 4.0"\n'
            "\n"
            "================================================================\n"
            "TITLE 1: SOMETHING\n"
            "================================================================\n"
            "Game          : not a header field\n"
            "license       : a later section must not overwrite the header one\n")
    f = parse_source_txt(text)
    assert f["source"].startswith("OpenStax (Rice University)"), f
    assert f["pulled"] == "2026-09-02"
    assert f["description"] == "Two OpenStax textbooks with extracted text."
    assert f["files"] == "4 files\n- a.txt (10 bytes)", repr(f["files"])
    assert f["license"].startswith("CC BY 4.0.") and "Creative Commons" in f["license"]
    assert "later section" not in f["license"], "first occurrence must win"
    assert "game" not in f

    with tempfile.TemporaryDirectory() as tmp:
        os.makedirs(os.path.join(tmp, "good"))
        os.makedirs(os.path.join(tmp, "nolicense"))
        os.makedirs(os.path.join(tmp, "bare"))
        Path(os.path.join(tmp, "good", "SOURCE.txt")).write_text(text, encoding="utf-8")
        Path(os.path.join(tmp, "nolicense", "SOURCE.txt")).write_text(
            "desc\n\nsource        : somewhere\n", encoding="utf-8")

        entries = collect(tmp)
        assert [n for n, _ in entries] == ["bare", "good", "nolicense"], entries
        assert dict(entries)["bare"] is None
        page = render(entries, tmp)
        assert "## good" in page and "**license**: CC BY 4.0." in page
        assert "bare: no SOURCE.txt" in page and "nolicense: no license field" in page
        assert page.count("## Problems") == 1

    print("[self-test] build_attribution ok")


if __name__ == "__main__":
    main()
